include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    require_trailing_commas: true
    avoid_redundant_argument_values: false
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    use_null_aware_elements: false
    unnecessary_underscores: false
